// src/pages/scene.tsx
import { Card, CardContent } from "@/components/ui/card"

export default function ScenePage() {
  return (
    <div className="flex items-center justify-center h-full">
      <Card>
        <CardContent className="pt-6">
          <p className="text-muted-foreground">
            3D Scene Editor — Coming in Phase 2
          </p>
        </CardContent>
      </Card>
    </div>
  )
}

// frontend/src/routes/scene/+page.svelte
<div class="h-full flex items-center justify-center">
  <div class="text-center">
    <h2 class="text-lg font-[--font-mono] text-[--color-text-muted] mb-2">3D Scene Editor</h2>
    <p class="text-sm font-[--font-mono] text-[--color-text-muted]">Coming in Phase 2</p>
    <p class="text-[11px] font-[--font-mono] text-[--color-text-muted] mt-1">Requires spatial mapping module</p>
  </div>
</div>
